Ft likes 164489935
andela/bad_ass-ah-backend pull request #32
Opened 2019-04-11 17:20 UTC by cop1fab

**What does this PR do?**

This PR allows a user to like or dislike an article. 

**Description of Task to be completed?**

Making sure a user can be able to like or dislike articles, both authored by a certain user and those not authored by that particular user.

**How should this be manually tested?**

In postman, on the routes api/articles/:articleId/likes or api/articles/:articleId/dislikes. to respectively like or dislike an article. 

**What are the relevant pivotal tracker stories?**

[#164489935](https://www.pivotaltracker.com/story/show/164489935)

**Screenshots (if appropriate)**
![image](https://user-images.githubusercontent.com/44478388/55977304-c7e07c00-5c8e-11e9-8569-788ae4534e38.png)
![image](https://user-images.githubusercontent.com/44478388/55977314-cc0c9980-5c8e-11e9-87f4-7570e33e8c56.png)
![image](https://user-images.githubusercontent.com/44478388/55977323-cfa02080-5c8e-11e9-8842-5976663c4b44.png)

2019-04-15 12:19 UTC, Paccy10 approved these changes

2019-04-15 14:56 UTC, nakiwuge requested changes
Good work @cop1fab  however, it would be better if the response when a user succesfully likes or dislikes an article contains` userId, articleId total number of likes and dislikes` .
 Something like ```{
message: "thanks for your support",
userId: "1",
article:"77"
likes: 1,
dislikes: 2
}```
Also, add the likes and dislike field to the article so that when someone retrieves an article they can view the total number of likes and dislikes .

2019-04-17 14:05 UTC, Jaman-dedy approved these changes

2019-04-17 15:25 UTC, blaisebakundukize commented
Good work @cop1fab however, your branch has conflicts. Update your develop branch then rebase from it for just resolving conflicts you have.

2019-04-24 09:36 UTC, nakiwuge approved these changes

2019-04-24 09:36 UTC, merged

2019-05-04 14:38 UTC, cop1fab commented
> Good work @cop1fab however, your branch has conflicts. Update your develop branch then rebase from it for just resolving conflicts you have.

Thank you for the feedback, I am going to rebase.